sonar.host.url=https://sonarcloud.io
sonar.organization=nourchenebenabdallahh
sonar.projectKey=OctFronteend
sonar.projectName=OctFronteend

sonar.sources=src/lib,src/store
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=sonar-report.xml

sonar.exclusions=**/.next/**,**/node_modules/**,**/public/**,**/src/app/**,**/src/components/**,**/src/hooks/**,**/src/layout/**
sonar.coverage.exclusions=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.d.ts,\
**/types/**,\
**/*.csv.ts,\
**/*.pdf.ts,\
**/prediction.tsx,\
**/inventaire.export.ts,\
**/*.api.ts,\
**/getServerAccessToken.ts,\
**/requireServerAccessToken.ts
